services:
  product:
    container_name: product
    build:
      context: .
      dockerfile: ./product-microservice/Product.Service/Dockerfile
    ports:
      - "8002:8080"
    restart: unless-stopped
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "RabbitMq__HostName=host.docker.internal"
      - "ConnectionStrings__Default=Server=host.docker.internal,1433;Database=Product;User Id=sa;Password=micR0S3rvice$;TrustServerCertificate=True"
      - "Authentication__AuthMicroserviceBaseAddress=http://auth:8080"
      - "OpenTelemetry__OtlpExporterEndpoint=http://jaeger:4317"
      - "OpenTelemetry__LogsOtlpExporterEndpoint=http://otel-collector:4317"
      - "OpenTelemetry__EnableConsoleExporters=false"
      - "OpenTelemetry__Environment=Development"

  order:
    container_name: order
    build:
      context: .
      dockerfile: ./order-microservice/Order.Service/Dockerfile
    ports:
      - "8001:8080"
    restart: unless-stopped
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "RabbitMq__HostName=host.docker.internal"
      - "ConnectionStrings__Default=Server=host.docker.internal,1433;Database=Order;User Id=sa;Password=micR0S3rvice$;TrustServerCertificate=True"
      - "Redis__Configuration=host.docker.internal:6379"
      - "OpenTelemetry__OtlpExporterEndpoint=http://jaeger:4317"
      - "OpenTelemetry__LogsOtlpExporterEndpoint=http://otel-collector:4317"
      - "OpenTelemetry__EnableConsoleExporters=false"
      - "OpenTelemetry__Environment=Development"

  basket:
    container_name: basket
    build:
      context: .
      dockerfile: ./basket-microservice/Basket.Service/Dockerfile
    ports:
      - "8000:8080"
    restart: unless-stopped
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "RabbitMq__HostName=host.docker.internal"
      - "Redis__Configuration=host.docker.internal:6379"
      - "OpenTelemetry__OtlpExporterEndpoint=http://jaeger:4317"
      - "OpenTelemetry__LogsOtlpExporterEndpoint=http://otel-collector:4317"
      - "OpenTelemetry__EnableConsoleExporters=false"
      - "OpenTelemetry__Environment=Development"

  inventory:
    container_name: inventory
    build:
      context: .
      dockerfile: ./inventory-microservice/Inventory.Service/Dockerfile
    ports:
      - "8005:8080"
    restart: unless-stopped
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "RabbitMq__HostName=host.docker.internal"
      - "ConnectionStrings__Default=Server=host.docker.internal,1433;Database=Inventory;User Id=sa;Password=micR0S3rvice$;TrustServerCertificate=True"
      - "Authentication__AuthMicroserviceBaseAddress=http://auth:8080"
      - "OpenTelemetry__OtlpExporterEndpoint=http://jaeger:4317"
      - "OpenTelemetry__LogsOtlpExporterEndpoint=http://otel-collector:4317"
      - "OpenTelemetry__EnableConsoleExporters=false"
      - "OpenTelemetry__Environment=Development"

  shipping:
    container_name: shipping
    build:
      context: .
      dockerfile: ./shipping-microservice/Shipping.Service/Dockerfile
    ports:
      - "8006:8080"
    restart: unless-stopped
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "RabbitMq__HostName=host.docker.internal"
      - "ConnectionStrings__Default=Server=host.docker.internal,1433;Database=Shipping;User Id=sa;Password=micR0S3rvice$;TrustServerCertificate=True"
      - "Authentication__AuthMicroserviceBaseAddress=http://auth:8080"
      - "OpenTelemetry__OtlpExporterEndpoint=http://jaeger:4317"
      - "OpenTelemetry__LogsOtlpExporterEndpoint=http://otel-collector:4317"
      - "OpenTelemetry__EnableConsoleExporters=false"
      - "OpenTelemetry__Environment=Development"

  payment:
    container_name: payment
    build:
      context: .
      dockerfile: ./payment-microservice/Payment.Service/Dockerfile
    ports:
      - "8007:8080"
    restart: unless-stopped
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "RabbitMq__HostName=host.docker.internal"
      - "ConnectionStrings__Default=Server=host.docker.internal,1433;Database=Payment;User Id=sa;Password=micR0S3rvice$;TrustServerCertificate=True"
      - "Authentication__AuthMicroserviceBaseAddress=http://auth:8080"
      - "OpenTelemetry__OtlpExporterEndpoint=http://jaeger:4317"
      - "OpenTelemetry__LogsOtlpExporterEndpoint=http://otel-collector:4317"
      - "OpenTelemetry__EnableConsoleExporters=false"
      - "OpenTelemetry__Environment=Development"

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: ./auth-microservice/Auth.Service/Dockerfile
    ports:
      - "8003:8080"
    restart: unless-stopped
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ConnectionStrings__Default=Server=host.docker.internal,1433;Database=Auth;User Id=sa;Password=micR0S3rvice$;TrustServerCertificate=True"
      - "Authentication__AuthMicroserviceBaseAddress=http://localhost:8003"
      - "OpenTelemetry__OtlpExporterEndpoint=http://jaeger:4317"
      - "OpenTelemetry__LogsOtlpExporterEndpoint=http://otel-collector:4317"
      - "OpenTelemetry__EnableConsoleExporters=false"
      - "OpenTelemetry__Environment=Development"

  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: ./api-gateway/ApiGateway/Dockerfile
    ports:
      - "8004:8080"
    restart: unless-stopped
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "Authentication__AuthMicroserviceBaseAddress=http://auth:8080"
      - "ReverseProxy__Clusters__auth-cluster__Destinations__default__Address=http://auth:8080"
      - "ReverseProxy__Clusters__product-cluster__Destinations__default__Address=http://product:8080"
      - "ReverseProxy__Clusters__basket-cluster__Destinations__default__Address=http://basket:8080"
      - "ReverseProxy__Clusters__order-cluster__Destinations__default__Address=http://order:8080"
      - "ReverseProxy__Clusters__inventory-cluster__Destinations__default__Address=http://inventory:8080"
      - "ReverseProxy__Clusters__shipping-cluster__Destinations__default__Address=http://shipping:8080"
      - "ReverseProxy__Clusters__payment-cluster__Destinations__default__Address=http://payment:8080"
      - "OpenTelemetry__OtlpExporterEndpoint=http://jaeger:4317"
      - "OpenTelemetry__LogsOtlpExporterEndpoint=http://otel-collector:4317"
      - "OpenTelemetry__EnableConsoleExporters=false"
      - "OpenTelemetry__Environment=Development"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  sql:
    container_name: sql
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=micR0S3rvice$"

  redis:
    container_name: redis
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.58
    ports:
      - "4317:4317"
      - "16686:16686"

  rabbitmq-exporter:
    container_name: rabbitmq-exporter
    image: kbudde/rabbitmq-exporter
    ports:
      - "9419:9419"
    environment:
      - RABBIT_URL=http://rabbitmq:15672
      - RABBIT_USER=guest
      - RABBIT_PASSWORD=guest
    depends_on:
      - rabbitmq

  redis-exporter:
    container_name: redis-exporter
    image: oliver006/redis_exporter
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis://redis:6379
    depends_on:
      - redis

  mssql-exporter:
    container_name: mssql-exporter
    image: awaragi/prometheus-mssql-exporter
    ports:
      - "4000:4000"
    environment:
      - SERVER=sql
      - PORT=1433
      - USERNAME=sa
      - PASSWORD=micR0S3rvice$
      - DATABASE=master
    depends_on:
      - sql

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus-config.yaml:/etc/prometheus/prometheus.yml
      - ./observability/alerts.yaml:/etc/prometheus/alerts.yaml
    depends_on:
      - rabbitmq-exporter
      - redis-exporter
      - mssql-exporter
      - alertmanager

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:v0.27.0
    ports:
      - "9093:9093"
    volumes:
      - ./observability/alertmanager.yaml:/etc/alertmanager/alertmanager.yml
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"

  loki:
    container_name: loki
    image: grafana/loki:3.1.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./observability/loki/loki-config.yaml:/etc/loki/loki-config.yaml

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.112.0
    command: ["--config=/etc/otel/otel-collector-config.yaml"]
    ports:
      - "4327:4317"
      - "4328:4318"
    volumes:
      - ./observability/otel-collector-config.yaml:/etc/otel/otel-collector-config.yaml
    depends_on:
      - loki

  grafana:
    container_name: grafana
    image: grafana/grafana:11.3.0
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
      - ./observability/grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus
      - loki
      - jaeger
