trigger:
  branches:
    include:
      - dev
      - staging
      - prod
      - deploy/*
  paths:
    include:
      - payment-microservice/*
      - shared-libs/*
      - Directory.Build.props
      - Infrastructure - Deployment/pipelines/templates/*

pr:
  branches:
    include:
      - '*'
  paths:
    include:
      - payment-microservice/*
      - shared-libs/*
      - Directory.Build.props
      - Infrastructure - Deployment/pipelines/templates/*

variables:
  - name: acrName
    value: $(AcrName)
  - name: acrServiceConnection
    value: $(AcrServiceConnection)

extends:
  template: ../Infrastructure - Deployment/pipelines/templates/build-stage.yml
  parameters:
    serviceName: payment
    solutionPath: payment-microservice/Payment.Service.slnx
    projectPath: payment-microservice/Payment.Service/Payment.Service.csproj
    dockerfilePath: payment-microservice/Payment.Service/Dockerfile
    acrName: $(acrName)
    acrServiceConnection: $(acrServiceConnection)
