// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shipping.Service.Infrastructure.Data.EntityFramework;

#nullable disable

namespace Shipping.Service.Migrations
{
    [DbContext(typeof(ShippingContext))]
    [Migration("20260526032839_SeedQaPhase3c_Shipping")]
    partial class SeedQaPhase3c_Shipping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shipping.Service.Domain.OrderConfirmation", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderId");

                    b.ToTable("OrderConfirmations");
                });

            modelBuilder.Entity("Shipping.Service.Domain.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CarrierKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LabelRef")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("QuotedPriceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("QuotedPriceCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Shipments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = "5ff2d67e-c6b5-4870-911f-79393ed416fd",
                            OrderId = new Guid("d0000000-0000-0000-0000-000000000001"),
                            Status = 0,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = "5ff2d67e-c6b5-4870-911f-79393ed416fd",
                            OrderId = new Guid("d0000000-0000-0000-0000-000000000002"),
                            Status = 1,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = "5ff2d67e-c6b5-4870-911f-79393ed416fd",
                            OrderId = new Guid("d0000000-0000-0000-0000-000000000003"),
                            Status = 2,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000004"),
                            CarrierKey = "fake-ground",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = "5ff2d67e-c6b5-4870-911f-79393ed416fd",
                            LabelRef = "label://qa/QA-TRACK-DISPATCHED-001",
                            OrderId = new Guid("d0000000-0000-0000-0000-000000000004"),
                            QuotedPriceAmount = 5.00m,
                            QuotedPriceCurrency = "USD",
                            Status = 3,
                            TrackingNumber = "QA-TRACK-DISPATCHED-001",
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = "5ff2d67e-c6b5-4870-911f-79393ed416fd",
                            OrderId = new Guid("d0000000-0000-0000-0000-000000000005"),
                            Status = 0,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000006"),
                            CarrierKey = "fake-ground",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = "5ff2d67e-c6b5-4870-911f-79393ed416fd",
                            LabelRef = "label://qa/QA-TRACK-DISPATCHED-FAIL-001",
                            OrderId = new Guid("d0000000-0000-0000-0000-000000000006"),
                            QuotedPriceAmount = 5.00m,
                            QuotedPriceCurrency = "USD",
                            Status = 3,
                            TrackingNumber = "QA-TRACK-DISPATCHED-FAIL-001",
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000007"),
                            CarrierKey = "fake-ground",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = "5ff2d67e-c6b5-4870-911f-79393ed416fd",
                            LabelRef = "label://qa/QA-TRACK-DISPATCHED-RETURN-001",
                            OrderId = new Guid("d0000000-0000-0000-0000-000000000007"),
                            QuotedPriceAmount = 5.00m,
                            QuotedPriceCurrency = "USD",
                            Status = 3,
                            TrackingNumber = "QA-TRACK-DISPATCHED-RETURN-001",
                            WarehouseId = 1
                        });
                });

            modelBuilder.Entity("Shipping.Service.Domain.ShipmentLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("ShipmentLines");

                    b.HasData(
                        new
                        {
                            Id = 90001,
                            ProductId = 9001,
                            Quantity = 2,
                            ShipmentId = new Guid("c0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 90002,
                            ProductId = 9001,
                            Quantity = 2,
                            ShipmentId = new Guid("c0000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = 90003,
                            ProductId = 9001,
                            Quantity = 2,
                            ShipmentId = new Guid("c0000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = 90004,
                            ProductId = 9001,
                            Quantity = 2,
                            ShipmentId = new Guid("c0000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = 90005,
                            ProductId = 9001,
                            Quantity = 2,
                            ShipmentId = new Guid("c0000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = 90006,
                            ProductId = 9001,
                            Quantity = 2,
                            ShipmentId = new Guid("c0000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = 90007,
                            ProductId = 9001,
                            Quantity = 2,
                            ShipmentId = new Guid("c0000000-0000-0000-0000-000000000007")
                        });
                });

            modelBuilder.Entity("Shipping.Service.Domain.ShipmentStatusHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("ShipmentStatusHistory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 90001,
                            OccurredAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ShipmentId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            Source = 0,
                            Status = 0
                        },
                        new
                        {
                            Id = 90002,
                            OccurredAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ShipmentId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            Source = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 90003,
                            OccurredAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ShipmentId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            Source = 0,
                            Status = 2
                        },
                        new
                        {
                            Id = 90004,
                            OccurredAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ShipmentId = new Guid("c0000000-0000-0000-0000-000000000004"),
                            Source = 0,
                            Status = 3
                        },
                        new
                        {
                            Id = 90005,
                            OccurredAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ShipmentId = new Guid("c0000000-0000-0000-0000-000000000005"),
                            Source = 0,
                            Status = 0
                        },
                        new
                        {
                            Id = 90006,
                            OccurredAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ShipmentId = new Guid("c0000000-0000-0000-0000-000000000006"),
                            Source = 0,
                            Status = 3
                        },
                        new
                        {
                            Id = 90007,
                            OccurredAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ShipmentId = new Guid("c0000000-0000-0000-0000-000000000007"),
                            Source = 0,
                            Status = 3
                        });
                });

            modelBuilder.Entity("Shipping.Service.Domain.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "WH-EAST",
                            Name = "East Coast Warehouse"
                        },
                        new
                        {
                            Id = 2,
                            Code = "WH-WEST",
                            Name = "West Coast Warehouse"
                        });
                });

            modelBuilder.Entity("Shipping.Service.Domain.Shipment", b =>
                {
                    b.OwnsOne("Shipping.Service.Domain.ShippingAddress", "ShippingAddress", b1 =>
                        {
                            b1.Property<Guid>("ShipmentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ShippingAddress_City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("ShippingAddress_Country");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("ShippingAddress_Line1");

                            b1.Property<string>("Line2")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("ShippingAddress_Line2");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("ShippingAddress_PostalCode");

                            b1.Property<string>("Recipient")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("ShippingAddress_Recipient");

                            b1.Property<string>("State")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ShippingAddress_State");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("Shipments");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.Navigation("ShippingAddress");
                });

            modelBuilder.Entity("Shipping.Service.Domain.ShipmentLine", b =>
                {
                    b.HasOne("Shipping.Service.Domain.Shipment", null)
                        .WithMany("Lines")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shipping.Service.Domain.ShipmentStatusHistoryEntry", b =>
                {
                    b.HasOne("Shipping.Service.Domain.Shipment", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shipping.Service.Domain.Shipment", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
