@Basket.Service_HostAddress = https://localhost:8000

### Get customer basket
GET {{Basket.Service_HostAddress}}/customer-1
Accept: application/json

###

### Create basket
POST {{Basket.Service_HostAddress}}/customer-1
Content-Type: application/json

{
  "productId": "1",
  "productName": "Test Product"
}

###

### Add product to basket
PUT {{Basket.Service_HostAddress}}/customer-1
Content-Type: application/json

{
  "productId": "2",
  "productName": "Another Product",
  "quantity": 2
}

###

### Delete product from basket
DELETE {{Basket.Service_HostAddress}}/customer-1/1

###

### Delete basket
DELETE {{Basket.Service_HostAddress}}/customer-1

###
