<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ECommerce.Shared.Kernel\ECommerce.Shared.Kernel.csproj" />
    <ProjectReference Include="..\ECommerce.Shared.EventBus\ECommerce.Shared.EventBus.csproj" />
    <ProjectReference Include="..\ECommerce.Shared.RabbitMq\ECommerce.Shared.RabbitMq.csproj" />
    <ProjectReference Include="..\ECommerce.Shared.AzureServiceBus\ECommerce.Shared.AzureServiceBus.csproj" />
    <ProjectReference Include="..\ECommerce.Shared.DeadLetter\ECommerce.Shared.DeadLetter.csproj" />
    <ProjectReference Include="..\ECommerce.Shared.Platform\ECommerce.Shared.Platform.csproj" />
    <ProjectReference Include="..\ECommerce.Shared.Contracts\ECommerce.Shared.Contracts.csproj" />
    <ProjectReference Include="..\ECommerce.Shared.Testing.Qa\ECommerce.Shared.Testing.Qa.csproj" />
  </ItemGroup>

</Project>
