trigger:
  branches:
    include:
      - dev
      - staging
      - prod
      - deploy/*
  paths:
    include:
      - inventory-microservice/*
      - shared-libs/*
      - Directory.Build.props
      - Infrastructure - Deployment/pipelines/templates/*

pr:
  branches:
    include:
      - '*'
  paths:
    include:
      - inventory-microservice/*
      - shared-libs/*
      - Directory.Build.props
      - Infrastructure - Deployment/pipelines/templates/*

variables:
  - name: acrName
    value: $(AcrName)
  - name: acrServiceConnection
    value: $(AcrServiceConnection)

extends:
  template: ../Infrastructure - Deployment/pipelines/templates/build-stage.yml
  parameters:
    serviceName: inventory
    solutionPath: inventory-microservice/Inventory.Service.slnx
    projectPath: inventory-microservice/Inventory.Service/Inventory.Service.csproj
    dockerfilePath: inventory-microservice/Inventory.Service/Dockerfile
    acrName: $(acrName)
    acrServiceConnection: $(acrServiceConnection)
