<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ECommerce.Shared.Contracts" Version="3.1.0" />
    <PackageReference Include="ECommerce.Shared.EventBus" Version="3.1.0" />
    <PackageReference Include="ECommerce.Shared.Messaging" Version="3.1.0" />
    <PackageReference Include="ECommerce.Shared.Platform" Version="3.1.0" />
    <PackageReference Include="ECommerce.Shared.Testing.Qa" Version="3.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Order.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Order.Service.LayoutAnalyzer\Order.Service.LayoutAnalyzer.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
