// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product.Service.Infrastructure.Data.EntityFramework;

#nullable disable

namespace Product.Service.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20260507000000_20260507_SeedQaPhase2_Product")]
    partial class _20260507_SeedQaPhase2_Product
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Product.Service.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 9001,
                            Description = "QA happy-path product",
                            Name = "product-happy",
                            Price = 10.00m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 9002,
                            Description = "QA payment-decline product (cents == 99)",
                            Name = "product-decline",
                            Price = 9.99m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 9003,
                            Description = "QA stock-shortage product (zero on hand)",
                            Name = "product-zero-stock",
                            Price = 10.00m,
                            ProductTypeId = 1
                        });
                });

            modelBuilder.Entity("Product.Service.Models.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Shoes"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Shorts"
                        });
                });

            modelBuilder.Entity("Product.Service.Models.Product", b =>
                {
                    b.HasOne("Product.Service.Models.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");
                });
#pragma warning restore 612, 618
        }
    }
}
