apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: orderservice
          image: <USERNAME>/orderservice:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RabbitMq__HostName
              value: rabbitmq-clusterip-service
            - name: ConnectionStrings__Default
              value: Server=mssql-clusterip-service,1433;Database=Order;User Id=sa;Password=micR0S3rvice$;TrustServerCertificate=True
            - name: Redis__Configuration
              value: redis-clusterip-service:6379
            - name: ProductService__BaseUrl
              value: http://product-clusterip-service:8080
            - name: OpenTelemetry__OtlpExporterEndpoint
              value: http://jaeger-clusterip-service:4317
            - name: OpenTelemetry__LogsOtlpExporterEndpoint
              value: http://otel-collector:4317
            - name: OpenTelemetry__SamplingRatio
              value: "0.1"
            - name: OpenTelemetry__ServiceVersion
              value: "1.0.0"
            - name: OpenTelemetry__Environment
              value: Production
---
apiVersion: v1
kind: Service
metadata:
  name: order-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: orderservice
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: orderservice-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: orderservice
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8080
