# One logical SQL Server with a database per SQL-backed service (auth, order,
# product, inventory, shipping, payment, saga), mirroring the Bicep sql.bicep set.
# The admin password is generated by random_password and lives only in state — the
# hardened azurerm backend is the mitigation (see terraform/README.md).
resource "random_password" "admin" {
  length      = 24
  min_lower   = 1
  min_upper   = 1
  min_numeric = 1
  min_special = 1
  # Avoid characters that are awkward in SQL connection strings (; ' " @ / space).
  override_special = "!#$%*-_=+"
}

resource "azurerm_mssql_server" "this" {
  name                          = var.name
  location                      = var.location
  resource_group_name           = var.resource_group_name
  version                       = "12.0"
  administrator_login           = var.admin_login
  administrator_login_password  = random_password.admin.result
  minimum_tls_version           = "1.2"
  public_network_access_enabled = true # switch to false + private endpoint for prod hardening
  tags                          = var.tags
}

# Let Azure services (AKS pods reaching the public endpoint) connect — the
# 0.0.0.0/0.0.0.0 sentinel is Azure's "Allow Azure services" rule, not the world.
resource "azurerm_mssql_firewall_rule" "allow_azure_services" {
  name             = "AllowAllAzureIPs"
  server_id        = azurerm_mssql_server.this.id
  start_ip_address = "0.0.0.0"
  end_ip_address   = "0.0.0.0"
}

# Serverless (GP_S_Gen5) with auto-pause is the cost-minimizing sandbox profile —
# the databases scale to zero when idle, matching costProfile == "minimal" in Bicep.
resource "azurerm_mssql_database" "this" {
  for_each = toset(var.database_names)

  name                        = each.key
  server_id                   = azurerm_mssql_server.this.id
  sku_name                    = var.sku_name
  collation                   = "SQL_Latin1_General_CP1_CI_AS"
  max_size_gb                 = var.max_size_gb
  min_capacity                = var.min_capacity
  auto_pause_delay_in_minutes = var.auto_pause_delay_in_minutes
  tags                        = var.tags
}
