// <auto-generated />
using System;
using Auth.Service.Infrastructure.Data.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Auth.Service.Migrations
{
    [DbContext(typeof(AuthContext))]
    [Migration("20260506132121_20260506_SeedQaData_Auth")]
    partial class _20260506_SeedQaData_Auth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Auth.Service.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d854813c-4a72-4afd-b431-878cba3ecf2a"),
                            PasswordHash = "AQAAAAIAAYagAAAAEDgcVTWsoKHvpybMHFtFOBxG0zYOvKUkB+xDTlq54OejnLzLBpFVNL0oIbrhJs7+hw==",
                            Role = "Administrator",
                            Username = "microservices@daonhan.com"
                        },
                        new
                        {
                            Id = new Guid("5ff2d67e-c6b5-4870-911f-79393ed416fd"),
                            PasswordHash = "AQAAAAIAAYagAAAAEDgcVTWsoKHvpybMHFtFOBxG0zYOvKUkB+xDTlq54OejnLzLBpFVNL0oIbrhJs7+hw==",
                            Role = "Customer",
                            Username = "customer-happy@qa.test"
                        },
                        new
                        {
                            Id = new Guid("be0d0a1d-c8fe-4b17-bf6a-051e8c809aa6"),
                            PasswordHash = "AQAAAAIAAYagAAAAEDgcVTWsoKHvpybMHFtFOBxG0zYOvKUkB+xDTlq54OejnLzLBpFVNL0oIbrhJs7+hw==",
                            Role = "Customer",
                            Username = "customer-decline@qa.test"
                        },
                        new
                        {
                            Id = new Guid("00faac97-9ae4-4b7f-b8aa-00e7c569dd66"),
                            PasswordHash = "AQAAAAIAAYagAAAAEDgcVTWsoKHvpybMHFtFOBxG0zYOvKUkB+xDTlq54OejnLzLBpFVNL0oIbrhJs7+hw==",
                            Role = "Customer",
                            Username = "customer-cancel@qa.test"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
