// <auto-generated />
using System;
using ECommerce.Shared.Infrastructure.DeadLetter;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Shared.Infrastructure.DeadLetter.Migrations
{
    [DbContext(typeof(DeadLetterDbContext))]
    [Migration("20260620000000_AddOriginToDeadLetterMessages")]
    partial class AddOriginToDeadLetterMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.Shared.Infrastructure.DeadLetter.Models.DeadLetterMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("int")
                        .HasColumnName("attempts");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DiscardReason")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("discard_reason");

                    b.Property<DateTime?>("DiscardedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("discarded_at");

                    b.Property<string>("DiscardedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("discarded_by");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("FailedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("failed_at");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("OriginalQueue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("original_queue");

                    b.Property<int>("Origin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("origin");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ReplayedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("replayed_at");

                    b.Property<string>("ReplayedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("replayed_by");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("routing_key");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("service");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("stack_trace");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("FailedAt");

                    b.HasIndex("Origin");

                    b.HasIndex("Status");

                    b.ToTable("dead_letter_messages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
